### ISSUE TITLE
Library name changed on npm?

### ISSUE THREAD

**Issue by laggingreflex** [statickidz/node-google-translate-skidz#10]
It seems the library name has changed from `node-google-translate-free` to `node-google-translate-skidz` on npm. But this github project is still called `-free`. And packages with both names exist on npm, `-free` being the outdated one. 

This might confuse users. It also creates problem for contributers, when you clone this repo from github it clones as `-free` and `npm link` links it with that name which the project using it isn't able to find.

Please unpublish the `-free` package from npm (you might need to email them to remove it entirely or have it redirected) and rename this github repo to `-skidz` (github handles redirects automatically I think)

**Comment by statickidz** [comment]
Hi, library its different on NPM because someone uploads node-google-translate-free to npm first with this code. I'll change repo name to mach with NPM name. Thanks.
