### ISSUE TITLE
translating on windows with electron app throwing an error 

### ISSUE THREAD

**Issue by alvapatrice** [statickidz/node-google-translate-skidz#16]
Couldn't retrieve a valid JSON response. Perhaps the API has changed, please let us know.

What's the problem with my application?

**Comment by statickidz** [comment]
Hi alvapatrice, I just [force build](https://travis-ci.org/statickidz/node-google-translate-skidz/builds/278475410) and its passing the tests. Maybe its something with your implementation. Can you give me more details in how you're working with that?

**Comment by alvapatrice** [comment]
here are the source code

'use strict';

Object.defineProperty(exports, "__esModule", {
	value: true
});

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

var _vuex = require('vuex');

var _nodeGoogleTranslateSkidz = require('node-google-translate-skidz');

var _nodeGoogleTranslateSkidz2 = _interopRequireDefault(_nodeGoogleTranslateSkidz);

var _languages = require('../utils/languages');

var _languages2 = _interopRequireDefault(_languages);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.default = {
	template: '<div class="translate-form" v-show="showTranslate">\n\t\t\t\t\t\t\t\t\t<select v-model="sourceSelectedLang" class="fl">\n\t\t\t\t\t\t\t\t\t\t<option v-for="lang in languages" :value="lang.value"> {{lang.text}} </option>\n\t\t\t\t\t\t\t\t\t</select>\n\t\t\t\t\t\t\t\t\t<button id="switch-languages" title="Switch Languages" @click="switchLangs"></button>\n\t\t\t\t\t\t\t\t\t<select v-model="targetSelectedLang" class="fr">\n\t\t\t\t\t\t\t\t\t\t<option v-for="lang in languages" :value="lang.value"> {{lang.text}} </option>\n\t\t\t\t\t\t\t\t\t</select>\n\t\t\t\t\t\t\t\t\t<textarea v-model="sourceText" placeholder="Source Text" maxlength="1000" @keyup.enter="translate"></textarea>\n\t\t\t\t\t\t\t\t\t<span class="trans-char-count fr db"> {{ sourceText.length }} / 1000 </span>\n\t\t\t\t\t\t\t\t\t<textarea v-model="targetText" placeholder="Target Text">{{targetText}}</textarea>\n\t\t\t\t\t\t\t\t\t<button id="clear-translate-btn" class="fl" @click="clearText">Clear</button>\n\t\t\t\t\t\t\t\t\t<div id="trans-loader" class="fl" v-show="transLoader">\n\t\t\t\t\t\t\t\t\t\t<div class="dot1"></div>\n\t\t\t\t\t\t\t\t\t\t<div class="dot2"></div>\n\t\t\t\t\t\t\t\t\t\t<div class="dot3"></div>\n\t\t\t\t\t\t\t\t\t\t<div class="dot4"></div>\n\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t<button id="translate-btn" class="fr royal" @click="translate">Translate</button>',
	data: function data() {
		return {
			sourceText: '',
			targetText: '',
			languages: _languages2.default,
			sourceSelectedLang: 'en',
			targetSelectedLang: 'tr',
			transLoader: false
		};
	},

	methods: {
		translate: function translate() {
			var _this = this;

			if (this.sourceText) {
				this.transLoader = true;
				try {
					(0, _nodeGoogleTranslateSkidz2.default)({
						text: this.sourceText,
						source: this.sourceSelectedLang,
						target: this.targetSelectedLang
					}, function (result) {
						if (result.translation) {
							_this.targetText = result.translation;
							_this.transLoader = false;
						} else _this.transLoader = false;
					});
				} catch (error) {
					this.transLoader = false;
				}
			}
		},
		switchLangs: function switchLangs() {
			var temp = this.sourceSelectedLang;
			this.sourceSelectedLang = this.targetSelectedLang;
			this.targetSelectedLang = temp;
			temp = this.sourceText;
			this.sourceText = this.targetText;
			this.targetText = temp;
		},
		clearText: function clearText() {
			this.sourceText = this.targetText = '';
		}
	},
	computed: _extends({}, (0, _vuex.mapGetters)({
		showTranslate: 'showTranslate'
	}))
};

I think there is no usage mistake.

**Comment by alvapatrice** [comment]
while trying to find where the problem is, I have tried to to make a request on the API url used in your lib/translate.js using Postman. 
1. here is my post request header 
![image2](https://user-images.githubusercontent.com/19281283/30732477-557ba2ae-9fa5-11e7-8d02-4c4511333b29.png)

2. Here is the body part
![image3](https://user-images.githubusercontent.com/19281283/30732486-62e59512-9fa5-11e7-9eb8-4633a5040c4a.png)

3. And it returns the not found error
![image1](https://user-images.githubusercontent.com/19281283/30732508-7aaa2866-9fa5-11e7-835b-e7adc57b98ad.png)

So can you figure out where should be the source of the problem? For me I think as long as with postman its self can't get a valid response, the API url might have a problem.

**Comment by statickidz** [comment]
@alvapatrice you're using old library version, please update to 1.1.1 in your package.json
