### ISSUE TITLE
Unable to translate not-default text

### ISSUE THREAD

**Issue by JuanjoSalvador** [statickidz/node-google-translate-skidz#2]
I'm trying to execute this code:

```
translate({
 q: 'text to translate',
 source: 'en',
 target: 'es'
}, function(result) {
  console.log(result);
}); 
```

And... output it's "texto" when should be "texto para traducir".

Google Translate API it's a paid service, I think Google is fucking this.

**Comment by statickidz** [comment]
Replace your "q" for "text" and it will work, I update readme because of changes.

```
translate({
 text: 'text to translate',
 source: 'en',
 target: 'es'
}, function(result) {
  console.log(result);
}); 
```

**Comment by JuanjoSalvador** [comment]
Uhhh. Great, thanks! :D
