### ISSUE TITLE
Problem with japanese strings

### ISSUE THREAD

**Issue by JuanjoSalvador** [statickidz/node-google-translate-skidz#3]
Trying to get a japanese text from Google Translate.

I get this.

> �����ɂ���'

Seems like a problem with charcode.

**Comment by JuanjoSalvador** [comment]
Solved using [`iconv`](https://github.com/ashtuchkin/iconv-lite) for UTF-8 conversion.

**Comment by tolya199178** [comment]
@JuanjoSalvador Can you comment sampe code for UTF-8 conversion.

**Comment by tolya199178** [comment]
[
 {
  "originalText": "name",
  "translatedText": "�̸�"
 },
 {
  "originalText": "this",
  "translatedText": "��"
 }
]
I am getting above result when english to korean translation.

**Comment by statickidz** [comment]
Thats just a console fonts stuff, I'll update with some changes and you'll see a example with some Korean text saved on a file

**Comment by tolya199178** [comment]
@statickidz  No, it is not console fonts stuff.
I have wirte resute code to file and there is chracter issue too.
fs.writeFile(filename, JSON.stringify(data, null, " "), "utf8");

**Comment by statickidz** [comment]
Check last update and install it from npm, then check the example with file

**Comment by tolya199178** [comment]
Thanks
