### ISSUE TITLE
Does not work anymore?

### ISSUE THREAD

**Issue by Avnerus** [statickidz/node-google-translate-skidz#8]
Hi!
Thank you for this module. It was working great, but now it seems that Google closed that 'hole'...
However, I think it should be possible to adapt to the change.

**Comment by tolya199178** [comment]
@statickidz , we have any solution?

**Comment by jerson** [comment]
:/ same here

**Comment by statickidz** [comment]
Sorry guys, no life-time to fix that in last days but I upload the fix in last commit, you can update to version to 1.0.1

**Comment by Avnerus** [comment]
Thank you!!
